# JDLogger Configuration File
# By WINGS7 💜

# Spigot: null
# Releases: https://github.com/WINGS07/JDLogger/releases
# BugReport/Suggestion: https://github.com/WINGS07/JDLogger/issues
# WIKI: https://github.com/WINGS07/JDLogger/wiki
