# JDLogger Configuration File
# WINGS-IO by N
# Spigot: https://www.spigotmc.org/resources/jdlogger-death-logger.99623/
# Releases: https://github.com/WINGS-IO/JDLogger/releases
# Bug Report/Suggestion: https://github.com/WINGS-IO/JDLogger/issues
# WIKI: https://github.com/WINGS-IO/JDLogger/wiki
