# JDLogger Configuration File
# By WINGS7N
# Spigot: https://www.spigotmc.org/resources/jdlogger-death-logger.99623/
# Releases: https://github.com/WINGS7N/JDLogger/releases
# BugReport/Suggestion: https://github.com/WINGS7N/JDLogger/issues
# WIKI: https://github.com/WINGS7N/JDLogger/wiki
