# JDLogger Configuration File
# By WINGS7 💜

# Spigot: https://www.spigotmc.org/resources/jdlogger-death-logger.85280/
# Releases: https://github.com/WINGS07/JDLogger_releases/releases
# BugReport/Suggestion: https://github.com/WINGS07/JDLogger_releases/issues
# WIKI: https://github.com/WINGS07/JDLogger_releases/wiki
