name: JDLogger
main: io.WINGS.JDLogger.Main
version: ${project.version}
api-version: 1.13
authors: [WINGS I.O. by N]
website: https://github.com/WINGS-IO/JDLogger/wiki
description: 'Plugin that records deaths and their details.'
load: POSTWORLD

commands:
    jdl:
        usage: /<command> r/tps/ping/u
        description: Main command.
        aliases: [deathlogger]
    jdllegacy:
        usage: /<command> <FileName>
        description: Legacy jdl or ndl inv data decode. (jdl and ndl data compatible)
        aliases: [deathloggerlegacy]
permissions:
  jdl.rollback:
    description: Allows rollback inventory via /jdl r
    default: op
  jdl.lowtps:
    description: Allows to survive if tps lower, than config value
    default: true
  jdl.bigping:
    description: Allows to survive if ping bigger, than config value
    default: true
  jdl.help:
    description: Allows get help via /jdl
    default: true
  jdl.gettps:
    description: Allows get JDLoggers's tps via /jdl tps
    default: true
  jdl.getping:
    description: Allows get player's ping via /jdl ping
    default: true
  jdl.upd:
    description: Allows update JDLogger via /jdl u
    default: op
  jdl.gc:
    description: Allows use /jdl gc
    default: op
